### ISSUE TITLE
npm start 后报错

### ISSUE THREAD

**Issue by bailangsyc** [heimashi/easy_mock_api#5]
我的报的也是这个错误
Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\shao\\easy_mock_api"
    at C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .jsx] (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)

**Comment by bailangsyc** [comment]
npm start不行是因为nodejs 版本太低了，但是可以启动后又报这个错误，帮忙看一下，新手一枚，谢谢
Couldn't find preset "es2015" relative to directory "C:\\Users\\shao\\easy_mock_api"
    at C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .jsx] (C:\Users\shao\easy_mock_api\node_modules\express-react-views\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
